[package]
name = "agent-core"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "complyx-agent"
path = "src/main.rs"

[package.metadata.deb]
maintainer = "Styxiner <@styxiner>"
copyright = "2026, Styxiner <@styxiner>"
license-file = ["LICENSE"]
extended-description = """\
Agente a instalar en los equipos a monitorear mediante políticas de seguridad centralizadas.
"""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
  [
    "target/release/complyx-agent",
    "/usr/bin",
    "755",
  ],
  [
    "config/agent.toml",
    "etc/complyx/agent.toml",
    "644",
  ],
  [
    "packagin/systemd/complyx-agent.service",
    "usr/lib/systemd/system/",
    "644",
  ],
]
conf-files = ["/etc/complyx/agent.toml"]
maintainer-scripts = "packagin/debian/"
systemd-units = [{ unit-name = "complyx-agent", enable = false }]

[package.metadata.rpm]
package = "complyx-agent"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
complyx-agent = { path = "/usr/bin/complyx-agent" }

[package.metadata.rpm.files]
"packagin/config/agent.toml" = { path = "/etc/complyx/agent.toml", mode = "644", config = true }
"packaging/systemd/complyx-agent.service" = { path = "/usr/lib/systemd/system/complyx-agent.service", mode = "644" }


[dependencies]
proto = { path = "../proto", features = ["client"] }
grpc-client = { path = "../grpc-client" }
policy-engine = { path = "../policy-engine" }
remediation-engine = { path = "../remediation-engine" }
local-db = { path = "../local-db" }

tokio = { version = "1", features = [
  "macros",
  "rt-multi-thread",
  "signal",
  "time",
  "fs",
] }

figment = { version = "0.10", features = ["toml", "env"] }
serde = { version = "1", features = ["derive"] }

#tracing = "0.1"
#tracing-suscriber = {version = "0.3", features = ["env-filter", "json", "fmt"]}

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "json",
  "fmt",
] }

anyhow = "1"
thiserror = "1"

uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tempfile = "3"
